[package]
name = "blunka-bpms"
version = "0.1.0"
authors = ["xusw<xusw@blunka.com>"]
edition = "2021"

[dependencies]
axum = { workspace = true }
axum-extra = { workspace = true }

byz_core = { path = "../core" }
